#!/bin/bash
ROFI_THEME="$HOME/.config/mango/rofi/power.rasi"
chosen=$(printf '%s\n' "[Cancel]" "Logout" "Shutdown" "Reboot" | \
    rofi -dmenu -i -p "Power Menu" -line-padding 4 -hide-scrollbar -theme "$ROFI_THEME")
case "$chosen" in
    "Logout") "$HOME/.config/mango/scripts/mango-ipc" dispatch quit ;;
    "Shutdown") systemctl poweroff ;;
    "Reboot") systemctl reboot ;;
    *) exit 0 ;;
esac
