splash = false
wallpaper {
         monitor = eDP-1
         path = /home/jfreitas/OneDrive/Pictures/Wallpapers/Paper_Architecture_by_Dmitri_Popov.jpg
         fit_mode = cover
    }
wallpaper {
         monitor = HDMI-A-1
         path = /home/jfreitas/OneDrive/Pictures/Wallpapers/dark-waves.jpg
         fit_mode = cover
    }
