vim.cmd([[ let g:tex_flavor = "latex"]] )
vim.cmd([[ let g:vimtex_quickfix_open_on_warning = 0]] )
vim.cmd([[ let g:vimtex_compiler_progname = 'nvr']] )
vim.cmd([[ let g:vimtex_view_method = 'zathura']] )
vim.cmd([[ let g:vimtex_quickfix_ignore_filters = [ 'Underfull', 'Overfull', 'specifier changed to',] ]])
