ZDOTDIR=$HOME/.config/zsh
. "$HOME/.cargo/env"

export EDITOR="nvim"
export VISUAL="nvim"

### ---- history config -------------------------------------
HISTFILE=~/.zsh_history

# How many commands zsh will load to memory.
HISTSIZE=10000

# How maney commands history will save on file.
SAVEHIST=1000000000

# History won't save duplicates.
setopt HIST_SAVE_NO_DUPS

# History won't show duplicates on search.
setopt HIST_FIND_NO_DUPS
