ZDOTDIR=$HOME/.config/zsh
if [ -d "$HOME/.cargo/env" ] ; then
    . "$HOME/.cargo/env"
fi

export EDITOR="nvim"
export VISUAL="nvim"

export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket

export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache

### ---- history config -------------------------------------
HISTFILE=~/.zsh_history

# How many commands zsh will load to memory.
HISTSIZE=10000

# How maney commands history will save on file.
SAVEHIST=1000000000

# History won't save duplicates.
setopt HIST_SAVE_NO_DUPS

# History won't show duplicates on search.
setopt HIST_FIND_NO_DUPS

if [ -d "$HOME/.bin" ] ; then
    PATH="$HOME/.bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

PATH="/usr/local/texlive/2023/bin/x86_64-linux:$PATH"
export PATH

neofetch

bindkey -e

bindkey '^[[H' beginning-of-line     # Home
bindkey '^[[F' end-of-line     # End
bindkey '^[[3~' delete-char     # Delete
bindkey '^?' backward-delete-char     # Backspace

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

autoload -U compinit; compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
_comp_options+=(globdots) # With hidden files

### --- Spaceship Config ------------------------------------

source $ZDOTDIR/themes/spaceship-prompt/spaceship.zsh-theme

SPACESHIP_PROMPT_ORDER=(
   user          # Username section
   dir           # Current directory section
   host          # Hostname section
   git           # Git section (git_branch + git_status)
   hg            # Mercurial section (hg_branch  + hg_status)
   exec_time     # Execution time
   line_sep      # Line break
   vi_mode       # Vi-mode indicator
   jobs          # Background jobs indicator
   exit_code     # Exit code section
   char          # Prompt character
)
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "


### ---- PLUGINS & THEMES -----------------------------------
source $ZDOTDIR/themes/spaceship-prompt/spaceship.zsh-theme
#source $ZDOTDIR/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fpath=($ZDOTDIR/plugins/zsh-completions/src $fpath)

source $ZDOTDIR/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

source $ZDOTDIR/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

#eval $(keychain --eval ~/.ssh/id_rsa)
#eval $(keychain --eval ~/.ssh/id_ecdsa)

# navigation
up () {
  local d=""
  local limit="$1"

  # Default to limit of 1
  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
    limit=1
  fi

  for ((i=1;i<=limit;i++)); do
    d="../$d"
  done

  # perform cd. Show error if cd fails
  if ! cd "$d"; then
    echo "Couldn't go up $limit dirs.";
  fi
}

# Backup a file with date
function backup() {
    cp "$1" "$1_`date +%Y-%m-%d_%H-%M-%S`_BACKUP"
}

# Update all git repos
function update_git_repos() {
  if [ $# -ne 1 ]; then
    echo "This function requires one parameter which must be a directory"
    return
  fi
  CURRENT_DIR=`pwd`
  echo "Updating all Git repos"
  for DIR in "$1"/*; do
    echo "\n========================================\n$DIR\n========================================"
    if [[ -d "$CURRENT_DIR/$DIR" ]]; then
      \cd "$CURRENT_DIR/$DIR"
      git status
      git pull origin $(git rev-parse --abbrev-ref HEAD)
    else
      echo "$CURRENT_DIR/$DIR not a directory"
    fi
  done
  \cd "$CURRENT_DIR"
}

source ~/.config/aliases/aliases

eval "$(starship init zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
#        . "/opt/miniconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/opt/miniconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<

