# Gerado dinamicamente por wallpaper-theme
# class                 border    bground   text      indicator child_border
client.focused          #ec7d13  #ec7d13  #171717       #dee495 #ec7d13
client.focused_inactive #393028   #171717       #d2c7bc       #393028   #393028
client.unfocused        #393028   #171717       #766460 #393028   #393028
client.urgent           #ea4544    #ea4544    #d2c7bc       #ea4544    #ea4544
