# Gerado dinamicamente por wallpaper-theme
# class                 border    bground   text      indicator child_border
client.focused          #aee0cb  #aee0cb  #15181e       #94a0d1 #aee0cb
client.focused_inactive #2a3c35   #15181e       #d2cbbc       #2a3c35   #2a3c35
client.unfocused        #2a3c35   #15181e       #606876 #2a3c35   #2a3c35
client.urgent           #cb8a86    #cb8a86    #d2cbbc       #cb8a86    #cb8a86
