# Gerado dinamicamente por wallpaper-theme
# class                 border    bground   text      indicator child_border
client.focused          #e0d8ae  #e0d8ae  #202d37       #94b7d1 #e0d8ae
client.focused_inactive #514d38   #202d37       #d2cbbc       #514d38   #514d38
client.unfocused        #514d38   #202d37       #6a7781 #514d38   #514d38
client.urgent           #cb8a86    #cb8a86    #d2cbbc       #cb8a86    #cb8a86
