#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

light-locker &
/usr/bin/dunst &
#polybar gondor&
bash /home/jfreitas/.config/polybar/forest/launch.sh &
nitrogen --restore& 
#xrandr --output DisplayPort-0 --mode 3840x2160 &
picom &

numlockx&
#dropbox&
setxkbmap -layout us -variant intl&
#nm-applet &
xmodmap /home/jfreitas/GitHub_Repos/dot/Gondor/config/Xmodmap

#bspc monitor DisplayPort-0 -d I II III IV V 
bspc monitor -d 1 2 3 4 5

#bspc monitor DisplayPort-1 -d VI
#bspc config border_width        2
#bspc config window_gap          5

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc config border_width                  2
bspc config window_gap                    5
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
#bspc rule -a Spotify desktop='^5'
bspc rule -a Virt-manager desktop='^4' state=floating
bspc rule -a Org.gnome.Nautilus state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

