#! /bin/sh
killall -q nitrogen
killall -q picom
killall -q dropbox

killall -q dunst
killall -q polybar
killall -q ibus-daemon
pkill polybar

pgrep -x sxhkd > /dev/null || sxhkd &

# checa se existem dois monitores definidos

MON=$(xrandr --listmonitors | grep Monitors | cut -b 11-)

# caso tenha, executa o setup para dois
if [[ $MON == 2 ]] ; then
     xrandr --output DP-0 --primary --left-of HDMI-0 --auto &
     bspc monitor DP-0 -d 1 2 3 4
     bspc monitor HDMI-0 -d 5 6 7 8
     # polybar example -c ~/.config/polybar/config.ini
     MON1=DP-0 polybar bar1 -c ~/.config/polybar/config_bar1.ini &

     MON2=HDMI-0  polybar bar2 -c ~/.config/polybar/config_bar2.ini &
else
    bspc monitor -d 1 2 3 4 5 6 7

    MONP=DP-0 polybar bar_main -c ~/.config/polybar/config_main.ini &
fi

############Window Settings ####################
bspc config border_width         1
bspc config window_gap           5
bspc config focus_follows_pointer   true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding      20

########## Border Colors #################
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#353b45"

######### Program settings ################
bspc rule -a spotify ='^5'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox desktop='^2'
bspc rule -a Zathura state=tiled
dunst &

######### Other Settings ################
xsetroot -cursor_name left_ptr &
#xbacklight -set 30
#xinput set-prop 12 309 1

######## MY picom :) ###################
picom --config ~/.config/picom/picom.conf --experimental-backends &

######## THe real beauty behind rice ####
#xwallpaper --zoom ~/wall/forest1.png
nitrogen --restore &

stalonetray ––background '#1e222a' --geometry 1x1-17+5 --max-geometry 10x1-17+5 --transparent true --tint-color '#1e222a' --tint-level 255 --grow-gravity NE --icon-gravity NW --icon-size 20 --sticky --window-type utility --window-strut top --skip-taskbar&

#sleep 5&
dropbox&
#setxkbmap -layout us -variant intl&
setxkbmap -layout us -variant intl
