#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

id=$HOME/.ssh/id_rsa

if [ -x /usr/bin/ssh-agent ] && [-f $id]; then
    eval `ssh-agent -s `
    ssh-add < /dev/null
fi
#picom -f&

xsetroot -cursor_name left_ptr

#numlockx&
#dropbox&
#setxkbmap -layout us -variant intl&
#nm-applet &
#xmodmap /home/jfreitas/GitHub_Repos/dot/Gondor/config/Xmodmap

session=${1:-xmonad}

case $session in
    i3|i3wm           ) exec i3;;
    gnome             ) exec gnome-session;;
    bp|bspwm          ) exec bspwm;;
    # Nenhuma sessão conhecida, tenta como comando
    *                 ) exec $1;;
esac
