# Gerado dinamicamente a partir de Debian_Wallpaper.png

[colors.primary]
background = "#171717"
foreground = "#d2c7bc"

[colors.cursor]
text = "#171717"
cursor = "#d2c7bc"

[colors.selection]
text = "#d2c7bc"
background = "#262626"

[colors.normal]
black   = "#262626"
red     = "#e72929"
green   = "#6ecf6e"
yellow  = "#cfc66e"
blue    = "#6e86cf"
magenta = "#cf6ecf"
cyan    = "#6ecfcf"
white   = "#c2b7ad"

[colors.bright]
black   = "#6b5a57"
red     = "#eb4e4d"
green   = "#8cd98c"
yellow  = "#d9d28c"
blue    = "#8c9fd9"
magenta = "#d98cd9"
cyan    = "#8cd9d9"
white   = "#e2dbd5"
