[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\\file:///home/jfreitas/Download_torrents/Rick.and.Morty.S09E02.1080p.x265-ELiTE[EZTVx.to].mkv)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x7f\0\0\0\x1\0\0\0\x1e\0\0\a~\0\0\x4\x7f\0\0\0\0\0\0\0\0\a\x80\0\0\0\x1\0\0\0\x1e\0\0\a~\0\0\x4\x7f)

[FullScreen]
pos=@Point(560 1136)
screen=@Rect(0 0 1920 1200)
wide=false

[MainWindow]
QtStyle=Padr\xe3o do sistema
ShowRemainingTime=true
adv-controls=0
bgSize=@Size(954 1032)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\b_\0\0\0\xdc\0\0\v\x80\0\0\x3\xb6\0\0\b`\0\0\0\xfa\0\0\v\x7f\0\0\x3\xb5\0\0\0\0\0\0\0\0\a\x80\0\0\b`\0\0\0\xfa\0\0\v\x7f\0\0\x3\xb5)

[RecentsMRL]
list=file:///home/jfreitas/Download_torrents/Rick.and.Morty.S09E02.1080p.x265-ELiTE[EZTVx.to].mkv, file:///home/jfreitas/Download_torrents/rick.and.morty.s09e01.1080p.web.h264-sylix[EZTVx.to].mkv, file:///home/jfreitas/Download_torrents/Family.Guy.S24E15.1080p.WEB.h264-EDITH[EZTVx.to].mkv, file:///home/jfreitas/GitHub/geometria_analitica/animacoes_manim/media/videos/parabola_rotacao_translacao/2160p60/AnimacaoParabola.mp4, file:///home/jfreitas/Download_torrents/Family.Guy.S24E14.1080p.WEB.h264-EDITH[EZTVx.to].mkv, file:///home/jfreitas/Download_torrents/Family.Guy.S24E13.1080p.WEB.h264-EDITH[EZTVx.to].mkv, file:///home/jfreitas/GitHub/geometria_analitica/animacoes_manim/media/videos/parabola_rotacao_translacao/480p15/AnimacaoParabola.mp4, file:///home/jfreitas/Download_torrents/Project.Hail.Mary.2026.2160p.WEB-DL.DDP5.1.Atmos.H.265-RDNYB.mkv, file:///home/jfreitas/Download_torrents/Severance%20S02E02%20Goodbye%20Mrs%20Selvig%201080P%20ATVP%20WEB-DL%20DDP5%201%20Atmos%20HEVC-X265%20POOTLED[EZTVx.to].mkv, file:///home/jfreitas/Download_torrents/Severance%20S02E01%20Hello%20Ms%20Cobel%201080p%20ATVP%20WEB-DL%20DDP5%201%20Atmos%20H%20264-FLUX[EZTVx.to].mkv, file:///home/jfreitas/Download_torrents/Harley%20Quinn%20S05E06%20Bottle%20My%20Heart%201080p%20AMZN%20WEB-DL%20DDP5%201%20H%20264-NTb[EZTVx.to].mkv
times=89078, 0, 274592, 0, 0, 0, 0, 480358, 0, 0, 0
