cursor #9eabac
cursor_text_color #adb7b7

foreground            #9eabac
background            #000c10
selection_foreground  #000c10
selection_background  #268bd3
url_color             #29a298

color0   #001419
color1   #cb642e
color2   #28a231
color3   #cabd24
color4   #0f998e
color5   #004b44
color6   #29a298
color7   #9aaaa8
color8   #6e7b7a
color9   #da8b60
color10  #5cc264
color11  #f3e973
color12  #41b2a8
color13  #64d2c9
color14  #96e2dc
color15  #e2eaea
